language: c

compiler: gcc

env:
#  - CROSS=
  - CROSS=pb

before_install: git clone https://github.com/pocketbook-free/SDK_481.git

install: make

before_script: touch empty-theme.cfg

script: ls -al
