language: c

compiler: gcc

cache:
  directories: SDK_481

env:
#  - CROSS=
  - CROSS=pb

before_install: if [[ "$CROSS" == "pb" ]]; then git clone https://github.com/pocketbook-free/SDK_481.git ; fi

install: make

before_script: touch empty-theme.cfg

script: ls -al
