language: c

compiler: gcc

env:
#  - CROSS=
  - CROSS=pb

before_install: git clone https://github.com/pocketbook-free/SDK_481.git

install: make

before_script: touch empty-theme.cfg

script: ls -al

deploy:
  provider: releases
  api_key: "5ec2956a5adf8ee8cc7447c0ed7e73cce5018c74"
  file: "pbtheme"
  skip_cleanup: true
  on:
    tags: true
