language: c

sudo: required

compiler: gcc

install: make

script:
    - ./pbtheme || true
    - ./pbtheme -u test-env/Line.pbt
    - cat theme.cfg
    - ./pbtheme -p test-env/Line.pbt theme.cfg || true
