language: c

compiler: gcc

sudo: false

cache:
  directories: SDK_481

env:
  - CROSS=
  - CROSS=pb

before_install: if [[ "$CROSS" == "pb" && ! -d SDK_481 ]]; then git clone https://github.com/pocketbook-free/SDK_481.git ; fi

install: make

before_script: touch empty-theme.cfg

script: ls -al

deploy:
  provider: releases
  api_key: "ba169a1d791b2a6349d79285ab3a0d171bb04fdf"
  file: "pbtheme"
  skip_cleanup: true
  on:
    condition: $RELEASE = true
#    tags: true
