language: c

compiler: gcc

addons:
  apt:
    packages: mingw32

before_install: git clone https://github.com/pocketbook-free/SDK_481.git

install: make

before_script: touch empty-theme.cfg

script:
  - ./pbtheme -h
  - ./pbtheme test-env/Line.pbt theme.cfg
  - test "`stat -c %s theme.cfg`" = 227394
  - ./pbtheme -r test-env/Line.pbt theme.cfg new_Line.pbt
  - test "`stat -c %s new_Line.pbt`" = 520290
  - ./pbtheme -e new_Line.pbt > new-theme.cfg
  - diff new-theme.cfg theme.cfg
  - ./pbtheme -r test-env/Line.pbt empty-theme.cfg new_Line.pbt
  - test "`stat -c %s new_Line.pbt`" = 494527

before_deploy:
  - rm pbtheme
  - make CROSS=pb
  - wget http://zlib.net/zlib-1.2.8.tar.gz
  - tar xvfz zlib-1.2.8.tar.gz
  - sed -e s/"PREFIX ="/"PREFIX = i586-mingw32msvc-"/ -i zlib-1.2.8/win32/Makefile.gcc
  - make -f win32/Makefile.gcc -C zlib-1.2.8
  - make CROSS=win
  - zip -9 pbtheme-${TRAVIS_BRANCH}.zip pbtheme pbtheme.exe README.md

deploy:
  provider: releases
  api_key:
    secure: "uhEDBNIy1iBEn5SisBAu2zAl+SedGIJBG5VlgqcuFNPexGV88Z5EGnTUamRwZ8nB5MD9RQzoHjJHbA5IHEe1dfH4r2O4BA9VpLkhFG8LbzGA44AOwfm8MYmdeXagxHFYUkGkDC2TW7jwh9iJXjmmDYw2OAhRB7ywr1YrxIhQuLeroW/UNshwHLUiZDN
MMxW/5IT7Neu+PyAjxP8N/h+ZeRIKM9eJ8EJX6JuXYeXgAt9j4GODLW2/PTm+GNrlwpy0+/b2G85wMb8Q3i/rm96JyO1m3ronKGCD8upxbcFLAEyLmvWFLeC5axNz8QtdjK9EMLXcKhT73Hc55WzNOebiKr4/plOK2r9BxvVoPfVfWsZWVsYY7QxyKipYvq1+EyTht
JeUeJHo2uBf2roV+oKkVnVWkDOJYKP8gfT5knBrcEEmnIoZnKW8DukJ7xlVY6YBdF962TPOkSfqIJTvAYLjRYuPP1zMfYqIKaWz+kVc3cMrJCp8SoNRohYbLvPSC6aTxGdMrqmr2fNuQt1ux41inCtJuOBleEElf9PntVuse1FWscQl3fqbWi2ILT0d+DnmZBEIyrh
1i39OOwIDnMTdjzOkZjONj9I0Ka4lAEoto4okMMuTi2AL2NDa0ZQkVbtVxIMC7U399Kwb1647J/1CA3WaKdoaaEk9WqbeaMf5tWw="
  file: "pbtheme-${TRAVIS_BRANCH}.zip"
  skip_cleanup: true
  on:
    tags: true
