language: c

compiler: gcc

addons:
  apt:
    packages: mingw32

before_install: git clone https://github.com/pocketbook-free/SDK_481.git

install: make

before_script: touch empty-theme.cfg

script:
  - ./pbtheme /?
  - ./pbtheme -h
  - ./pbtheme --help
  - ./pbtheme test-env/Line.pbt theme.cfg
  - test "`stat -c %s theme.cfg`" = 610347
  - ./pbtheme -r test-env/Line.pbt theme.cfg new_Line.pbt
  - test "`stat -c %s new_Line.pbt`" = 599195
  - ./pbtheme -e new_Line.pbt > new-theme.cfg
  - diff new-theme.cfg theme.cfg
  - echo 1 >> new-theme.cfg
  - ./pbtheme --extract new_Line.pbt > new-theme.cfg
  - diff new-theme.cfg theme.cfg
  - ./pbtheme --replace test-env/Line.pbt empty-theme.cfg new_Line.pbt
  - test "`stat -c %s new_Line.pbt`" = 546757

before_deploy:
  - rm pbtheme
  - make CROSS=pb
  - wget http://zlib.net/zlib-1.2.11.tar.gz
  - tar xvfz zlib-1.2.11.tar.gz
  - sed -e s/"PREFIX ="/"PREFIX = i586-mingw32msvc-"/ -i zlib-1.2.11/win32/Makefile.gcc
  - make -f win32/Makefile.gcc -C zlib-1.2.11 libz.a
  - make CROSS=win LDFLAGS="-Izlib-1.2.11 -Lzlib-1.2.11"
  - zip -9 pbtheme-${TRAVIS_BRANCH}-win.zip pbtheme.exe README.md
  - zip -9 pbtheme-${TRAVIS_BRANCH}-pb.zip pbtheme README.md

deploy:
  provider: releases
  api_key:
    secure: RYthkSir88D77SeTT7W+fYnvZsqrTvSzZkZ0KntpBQKiS4MDX/N9KrsutoRgPp9AJkQU76eyZYXYKw2loMrYVI4mG1HoCy0yIITTK9OojBdyrGni5FOzod47Uu7xBMEksRX2SIvStyVQW826DSDa0a3UQxhjx2bkzScLAt/xkpqGLTdo4nRMprksjSAOhyH+LNHeP5QNBFAy6S4wf7PeNJfuXMdXROiaRmeoOUgHfSCcUIIIg4Xj9Ms4Qz1T1mfnOK4ZY64PcDDagKTKE/07w6WgoZVUlPTWjhLUS5spboDclv09VEA/ENFtRIK4ISQwHsD3Za/2ckt5KUOHPKcxXrGZL+KIFyunia/ty1DVlZJrlxVmqJAy38aG3smCkkApy8ZcItG02RRpOEEetYrlEDv2C+o7p6bOTfuyG8mJpsBJueCta8Pe5Ke/YO45x9oVE/H/u5cw6V2sshIzLRbrnJGW4tNzdw7Xn2MprZhcNV/0jbf4ImuHQZAv4JAzMRZcJkEiwVqrslgHPQtvbZUtv9W2pKwx1/2iYXZ2uABtfM21TaqyIcffwBkEFFOSJiYllkurrxXui2hHrwcxwZoTkljeC2pyOxJ51BI8Rr8o37MHD6J5JYRbbJ+uY/QNHdD40u6Tx5SecyjRr3aY3klTv1w3DDlX/GsTEGJZEd7UlAg=
  file:
    - "pbtheme-${TRAVIS_BRANCH}-win.zip"
    - "pbtheme-${TRAVIS_BRANCH}-pb.zip"
  skip_cleanup: true
  on:
    repo: Lighting/pbtheme
    tags: true
