language: c

compiler: gcc

cache:
  directories: .success

env:
  - CROSS=
  - CROSS=pb

before_install: if [ "$CROSS" = pb ]; then git clone https://github.com/pocketbook-free/SDK_481.git ; fi

install: make

before_script: touch empty-theme.cfg

script:
  - if [ -z "$CROSS" ]; then ./pbtheme -h ; fi
    
  - if [ -z "$CROSS" ]; then ./pbtheme test-env/Line.pbt theme.cfg ; fi
  - if [ -z "$CROSS" ]; then test "`stat -c %s theme.cfg`" = 227394 ; fi
  
  - if [ -z "$CROSS" ]; then ./pbtheme -p test-env/Line.pbt theme.cfg ; fi
  - if [ -z "$CROSS" ]; then test "`stat -c %s test-env/Line.pbt`" = 520290 ; fi

  - if [ -z "$CROSS" ]; then ./pbtheme -u test-env/Line.pbt > new-theme.cfg ; fi
  - if [ -z "$CROSS" ]; then diff new-theme.cfg theme.cfg ; fi
  
  - if [ -z "$CROSS" ]; then ./pbtheme -p test-env/Line.pbt empty-theme.cfg ; fi
  - if [ -z "$CROSS" ]; then test "`stat -c %s test-env/Line.pbt`" = 494527 ; fi

after_success: if [ -z "$CROSS" ]; then touch .success ; fi

after_failure: rm -f .success

deploy:
  provider: releases
  api_key: "b11c031366e49535b18696782cff6215d1b0c313"
  file: "pbtheme"
  skip_cleanup: true
  on:
    repo: Lighting/pbtheme
    condition: $CROSS = pb
    condition: [ -e .success ]
    tags: true
