language: c

sudo: required

compiler: gcc

install: make

script:
    - ./pbtheme -h
    - ./pbtheme test-env/Line.pbt > theme.cfg
    - test -s theme.cfg
    - ./pbtheme -p test-env/Line.pbt theme.cfg
